// Posadas zones configuration - Static data
export const POSADAS_COORDS = {
  latitude: -27.3671,
  longitude: -55.8961,
};

export const POSADAS_ZONES = [
  {
    id: 1,
    name: "Centro",
    lat: -27.3671,
    lng: -55.8961,
    description: "Centro histórico y comercial",
  },
  {
    id: 2,
    name: "Villa Cabello",
    lat: -27.358,
    lng: -55.902,
    description: "Zona residencial norte",
  },
  {
    id: 3,
    name: "Itaembé Miní",
    lat: -27.345,
    lng: -55.885,
    description: "Barrio costero",
  },
  {
    id: 4,
    name: "Villa Urquiza",
    lat: -27.375,
    lng: -55.87,
    description: "Zona sur residencial",
  },
  {
    id: 5,
    name: "San José",
    lat: -27.39,
    lng: -55.89,
    description: "Barrio obrero",
  },
  {
    id: 6,
    name: "Nemesio Parma",
    lat: -27.38,
    lng: -55.91,
    description: "Zona oeste",
  },
  {
    id: 7,
    name: "Villa Sarita",
    lat: -27.36,
    lng: -55.88,
    description: "Barrio residencial",
  },
  {
    id: 8,
    name: "Bajada Vieja",
    lat: -27.365,
    lng: -55.895,
    description: "Zona histórica portuaria",
  },
  {
    id: 9,
    name: "Villa Blosset",
    lat: -27.352,
    lng: -55.875,
    description: "Barrio residencial norte",
  },
  {
    id: 10,
    name: "San Roque",
    lat: -27.382,
    lng: -55.865,
    description: "Zona sur-este",
  },
  {
    id: 11,
    name: "Villa Lanús",
    lat: -27.348,
    lng: -55.915,
    description: "Barrio periférico",
  },
  {
    id: 12,
    name: "El Porvenir",
    lat: -27.395,
    lng: -55.875,
    description: "Zona industrial",
  },
  {
    id: 13,
    name: "Villa Lourdes",
    lat: -27.335,
    lng: -55.89,
    description: "Barrio norte",
  },
  {
    id: 14,
    name: "Yacyretá",
    lat: -27.4,
    lng: -55.88,
    description: "Zona de la represa",
  },
  {
    id: 15,
    name: "Villa Alberti",
    lat: -27.37,
    lng: -55.92,
    description: "Barrio oeste",
  },
  {
    id: 99,
    name: "Otros",
    lat: -27.3671,
    lng: -55.8961,
    description: "Otra ubicación - marcar en el mapa",
  },
];